twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['common/form/theme.html.twig']
    globals:
        awsPublicUrl: '%env(AWS_PUBLIC_URL)%'
        baseUrl: '%env(BASE_URL)%'
when@test:
    twig:
        strict_variables: true
