version: "3.8"

volumes:
  database: {}

services:
  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: moment
      POSTGRES_PASSWORD: moment
      POSTGRES_USER: moment
    ports:
      - '5432:5432'
    volumes:
      - 'database:/var/lib/postgresql@16/data:rw'

  php:
    build:
      context: ./docker/php
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www/moment
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - database
      - redis

  php_worker:
    build:
      context: ./docker/php
    command: 'bin/console messenger:consume async --time-limit=300 --memory-limit=256M --limit=50'
    restart: always
    volumes:
      - ./:/var/www/moment
    depends_on:
      - database
      - redis

  nginx:
    image: nginx:stable-alpine
    ports:
      - '8000:80'
    volumes:
      - ./:/var/www/moment
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

  redis:
    image: redis:5-alpine
    ports:
      - 6379:6379

  mailer:
    image: schickling/mailcatcher
    ports:
      - 1025:1025
      - 1080:1080
