controllers:
    resource: ../src/Infrastructure/Controller/
    type: attribute

app_controllers:
    resource: ../src/Infrastructure/Controller/App
    type: attribute
    prefix: /app
    trailing_slash_on_root: false

fragment_controllers:
    resource: ../src/Infrastructure/Controller/Fragments
    type: attribute
    prefix: /_fragments
    trailing_slash_on_root: false

app_logout:
    path: /logout
    methods: GET
